server:
  port: 6800

spring:
  application:
    name: pmhub-auth
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms

token:
  header: Authorization
  secret: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
  expireTime: 600

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  file:
    name: logs/${spring.application.name}/info.log
