server:
  port: 6880

spring:
  application:
    name: pmhub-gateway
  cloud:
    gateway:
      routes:
        - id: pmhub-auth
          uri: lb://pmhub-auth
          predicates:
            - Path=/auth/**
        - id: pmhub-system
          uri: lb://pmhub-system
          predicates:
            - Path=/system/**
        - id: pmhub-project
          uri: lb://pmhub-project
          predicates:
            - Path=/project/**
        - id: pmhub-workflow
          uri: lb://pmhub-workflow
          predicates:
            - Path=/workflow/**
        - id: pmhub-job
          uri: lb://pmhub-job
          predicates:
            - Path=/schedule/**

security:
  ignore:
    whites:
      - /auth/login
      - /auth/register
      - /auth/logout
      - /auth/refresh
      - /auth/smsLogin
      - /auth/socialLogin
      - /auth/bindSocial
      - /auth/unbindSocial
      - /code
      - /auth/code
      - /auth/smsCaptcha
      - /csrf
      - /swagger-ui/**
      - /swagger-resources/**
      - /v2/api-docs
      - /v3/api-docs
      - /webjars/**
      - /actuator/**
      - /druid/**
      - /favicon.ico
  captcha:
    enabled: true
    type: math
  xss:
    enabled: true
    excludeUrls:
      - /system/notice

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  file:
    name: logs/${spring.application.name}/info.log
